
state.savepoints.dir: file:///tmp/SAVEPOINT_DIR_NAME
high-availability: NONE
parallelism.default: 1
#FIXME: reversing flink default order
classloader.resolve-order: parent-first

taskmanager.memory.jvm-metaspace.size: 512m
