name: Build

on: 
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      nussknacker_version:
        description: "Nussknacker version"
        required: false
        type: string

env:
  NUSSKNACKER_VERSION: ${{ inputs.nussknacker_version }}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache ivy packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-sbt
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.11"
      - name: Tests
        run: sbt test it:test
