name: Build

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      nussknacker_version:
        description: "Nussknacker version"
        required: false
        type: string

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache ivy packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-sbt
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.11"

      - name: Run Tests for Nussknacker version from workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          NUSSKNACKER_VERSION: ${{ github.event.inputs.nussknacker_version }}
        run: sbt 'set ThisBuild / version := "$NUSSKNACKER_VERSION"' +test it:test

      - name: Run Tests for Nussknacker version from branch
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: sbt +test it:test
